In [2]:
from fastai.collab import * 
from fastai.tabular.all import *

In [3]:
path = untar_data(URLs.ML_100k)

In [4]:
ratings = pd.read_csv(path/'u.data',delimiter='\t', header=None, 
                      names=['user','movie','rating','timestamp']) 
ratings.head()

   user  movie  rating  timestamp
0   196    242       3  881250949
1   186    302       3  891717742
2    22    377       1  878887116
3   244     51       2  880606923
4   166    346       1  886397596

In [9]:
movies=pd.read_csv(path/'u.item',delimiter='|', encoding='latin-1',usecols=(0,1),names=('movie','title'),header=None)

In [11]:
movies.head()

   movie              title
0      1   Toy Story (1995)
1      2   GoldenEye (1995)
2      3  Four Rooms (1995)
3      4  Get Shorty (1995)
4      5     Copycat (1995)

In [14]:
ratings = ratings.merge(movies)
ratings

,user,movie,rating,timestamp,title
0,196,242,3,881250949,Kolya (1996)
1,63,242,3,875747190,Kolya (1996)
2,226,242,5,883888671,Kolya (1996)
3,154,242,3,879138235,Kolya (1996)
4,306,242,5,876503793,Kolya (1996)
...,...,...,...,...,...
99995,840,1674,4,891211682,Mamma Roma (1962)
99996,655,1640,3,888474646,"Eighth Day, The (1996)"
99997,655,1637,3,888984255,Girls Town (1996)
99998,655,1630,3,887428735,"Silence of the Palace, The (Saimt el Qusur) (1994)"
99999,655,1641,3,887427810,Dadetown (1995)

In [15]:
dls=CollabDataLoaders.from_df(ratings,item_name='title',bs=64)

In [16]:
dls.show_batch()

In [18]:
lrnr = collab_learner(dls,n_factors=50,y_range=(0.5,5))