# (노트) 기울기소멸, 추천시스템

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [빅데이터분석]

## 기울기소멸

### 고요속의 외침

`-` https://www.youtube.com/watch?v=ouitOnaDtFY

`-` 중간에 한명이라도 잘못말한다면..

### 정의

`-` In machine learning, the vanishing gradient problem is encountered when training artificial neural networks with gradient-based learning methods and backpropagation.

### 이해

`-` 당연한거 아닌가? 
- 그래디언트 기반의 학습(그래디언트 기반의 옵티마이저): 손실함수의 기울기를 통하여 업데이트 하는 방식
- 역전파: 손실함수의 기울기를 구하는 테크닉(체인룰 + $\alpha$). 구체적으로는 (1) 손실함수를 여러단계로 쪼개고 (2) 각 단계의 미분을 각각 구하고 (3) 그것들을 모두 곱하여 기울기를 계산한다. 
- 0근처의 숫자를 계속 곱하면 터지거나 0으로 간다. (사실 안정적인 기울기가 나올거라고 보는것이 이상한것임)

In [206]:
import numpy as np

In [207]:
grads = np.random.uniform(low=-2,high=2,size=100)
grads

array([ 0.18688288,  0.43450847, -0.87513215,  1.35976661, -1.67602921,
       -1.94881797,  0.28000878, -0.07982773,  0.41098101,  1.44913431,
        1.42155413,  0.30179395, -1.11750978, -1.03629995,  1.73194045,
        1.30429018, -1.85441508, -0.23849127,  1.69550035,  1.08930237,
        0.61166949, -1.55165233,  1.35400582, -0.79701747,  0.80542101,
       -1.63942602,  1.5169811 , -0.99256516,  1.12927938, -0.60001878,
       -0.79629782, -1.41639694, -1.60737528, -0.810134  ,  1.46868468,
        0.80995697, -0.01861418,  1.870188  ,  0.7237886 ,  1.94490223,
        0.30018531,  0.7239008 , -1.49830624,  0.35257188,  1.54092802,
        0.37818125,  1.85990611, -1.03105941,  0.5865016 , -1.98180695,
       -0.27474677,  0.88501944,  0.47957049,  1.97015467,  1.18178691,
        1.35343833,  1.84192922, -0.16687519, -0.63599077,  1.78165492,
       -1.38607268, -0.6363796 ,  1.26337952, -1.82063191,  1.92715124,
        0.56908745, -1.44857969, -0.44694881,  1.12397453,  0.81900019,
       -1.34730467, -0.03100787, -1.98911877,  1.26495344,  0.4073905 ,
       -1.96826953,  1.93068033,  1.07119525, -0.05285845,  1.43202408,
        0.10627962, -1.24520154,  1.28336267,  1.24564003,  0.45895504,
        0.05938386, -0.33004816,  1.71594089, -1.92451146, -1.67093832,
        1.64631833, -0.55316687,  0.43782105, -1.87975355, -1.89361645,
       -0.06089341,  0.571681  , -0.39305498, -1.40057471, -0.97509085])

In [208]:
grads.prod()

-4.231809904440714e-11

- 기울기가 소멸함

In [209]:
grads = np.random.uniform(low=-3,high=3,size=100)
grads.prod()

16676775121011.598

- 기울기가 폭발함

In [210]:
grads = np.random.uniform(low=-3,high=3,size=100)
grads.prod()

-504691.96433542186

In [244]:
grads = np.random.uniform(low=-1,high=3.5,size=100)
grads.prod()

-5.898185033226975e-06

`-` 도깨비: 기울기가 소멸하기도 하고 터지기도 한다.

### 해결책 (기울기 소멸에 대한 해결책)

> Note: 잘 정리되어있는게 없어서 제 머리속에서 정리했습니다. 부정확할수 있어요.

`-` 개념 
- 데이터 $\to$ (아키텍처, 손실함수, 역전파, 업데이트)

`-` Multi-level hierarchy 
- 여러층을 쪼개서 학습하자 $\to$ 어떻게?... 사전학습, 층별학습. 
- 기울기소실문제를 해결하여 딥러닝을 유행시킨 태초의 방법임. 
- 입력자료의 전처리도 여기에 해당함 
- 결국 입력자료를 바꾼뒤에 학습하는 형태

`-` Faster hardware 
- GPU를 중심으로 한 테크닉. 
- 근본적인 문제해결은 아니라는 힌튼의 비판. 
- CPU를 쓸때보다 GPU를 쓰면 약간 더 깊은 모형을 학습할 수 있다 정도?

`-` ResNet 
- 훌륭한 접근법중 하나임 
- 아키텍처를 변경하는 방법이지만, 사실상 손실함수를 스무딩 시켜버리는 기법으로 이해해도 된다. 
- 숏컷이라는 아키텍처를 추가하여 이리저리 실험해보니까 손실함수가 스무딩 되었다! <-- 이런게 아니라.. 
- 손실함수를 스무딩하기 위해서는 층별의 차이(residual)만 학습하는게 유리할것 같다. 그런데 그것을 위한 효과를 주기 위해 아키텍처를 설계하려면 단지 숏컷을 만들기만 하면 된다. <-- 이런 모티브였을 것이다..

`-` 활성화함수의 변경 
- 렐루의 개발 $\to$ 특정노드가 죽음 $\to$ 리키렐루의 개발

`-` 배치정규화 
- 어쩌다보니 되는 것. 
- 배치정규화는 공변량 쉬프트를 잡기위한 방법임. 그런데 기울기소멸에도 효과가 있음. 현재는 기울기 소멸에 대한 해결책으로 빠짐없이 언급되는 내용. 하지만 2015년의 원래 논문에서는 기울기소멸에 대한 언급없음 (https://arxiv.org/pdf/1502.03167.pdf)
- 심지어 배치정규화는 오버피팅을 잡는것에도 효과가 있음 (이것은 논문에 언급있음)

`-` **기울기를 안구하면 안되나?**
- 베이지안 최적화기법: (https://arxiv.org/pdf/1807.02811.pdf) $\to$ GPU를 어떻게써? $\to$ 진짜 엄청느려요.. 지옥입니다.. 
- 강화학습?

## 딥러닝 + 머신러닝 공부를 위한 교재

`-` 기계학습, 오일석 (http://www.yes24.com/Product/Goods/57537091) 
- 좋은 교재에요.. 
- 딥러닝 초급내용을 커버할 수 있습니다..

`-` 심층학습, 이안굿펠로우 (https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=171345378) 
- 이안굿펠로우는 GAN을 만든사람입니다. 
- 거의 표준임. 
- 번역상태가 너무 너무 안좋아요.

`-` 머신러닝교재들 
- 패턴인식: 
- Element of Statistical Learning

## 추천시스템

### import

In [490]:
import torch 
import matplotlib.pyplot as plt

In [572]:
from fastai.collab import * 
from fastai.tabular.all import *

### data (시뮬레이션)

In [573]:
user = list(range(1,101))
item = list(range(1,21))
_lst = [[0,0,4.2]]

In [574]:
def f(u,i): 
    if u<=50 and i<=10: 
        return np.random.randn(1)[0]*0.2+4 
    elif u<=50 and i>10:
        return np.random.randn(1)[0]*0.2+1 
    elif u>50 and i<=10:
        return np.random.randn(1)[0]*0.2+1 
    elif u>50 and i>10:
        return np.random.randn(1)[0]*0.2+4 
        
for u in user:
    _item = np.random.choice(list(range(1,21)),size=10,replace=False).tolist()
    for i in _item:
        _lst.append([u,i,f(u,i)])

In [575]:
_df1=pd.DataFrame(_lst[1:],columns=['user','item','rating'])
_df1

     user  item    rating
0       1    15  1.084308
1       1    17  0.906524
2       1    14  0.603118
3       1     1  4.149209
4       1    11  1.142659
..    ...   ...       ...
995   100    17  4.164773
996   100    10  1.177387
997   100     7  1.094826
998   100    12  4.136731
999   100    14  4.026915

[1000 rows x 3 columns]

In [576]:
['커피'+str(i+1) for i in range(10)]+['홍차'+str(i+1) for i in range(10)]

['커피1',
 '커피2',
 '커피3',
 '커피4',
 '커피5',
 '커피6',
 '커피7',
 '커피8',
 '커피9',
 '커피10',
 '홍차1',
 '홍차2',
 '홍차3',
 '홍차4',
 '홍차5',
 '홍차6',
 '홍차7',
 '홍차8',
 '홍차9',
 '홍차10']

In [577]:
_df2 = pd.DataFrame({'item':list(range(1,21)), 'item_name':['커피'+str(i+1) for i in range(10)]+['홍차'+str(i+1) for i in range(10)]})
_df2

    item item_name
0      1       커피1
1      2       커피2
2      3       커피3
3      4       커피4
4      5       커피5
5      6       커피6
6      7       커피7
7      8       커피8
8      9       커피9
9     10      커피10
10    11       홍차1
11    12       홍차2
12    13       홍차3
13    14       홍차4
14    15       홍차5
15    16       홍차6
16    17       홍차7
17    18       홍차8
18    19       홍차9
19    20      홍차10

In [578]:
df= _df1.merge(_df2).sort_values('user') 
df

     user  item    rating item_name
0       1    15  1.084308       홍차5
147     1     1  4.149209       커피1
211     1    11  1.142659       홍차1
264     1     5  4.033415       커피5
319     1     4  4.078139       커피4
..    ...   ...       ...       ...
572   100    18  4.104276       홍차8
95    100    17  4.164773       홍차7
146   100    14  4.026915       홍차4
367   100     4  0.838720       커피4
999   100     7  1.094826       커피7

[1000 rows x 4 columns]

In [579]:
df.to_csv('2021-11-30-recommend.csv',index=False)

### data (load)

`-` 가짜 자료

In [580]:
pd.read_csv("2021-11-30-recommend.csv")

     user  item    rating item_name
0       1    15  1.084308       홍차5
1       1     1  4.149209       커피1
2       1    11  1.142659       홍차1
3       1     5  4.033415       커피5
4       1     4  4.078139       커피4
..    ...   ...       ...       ...
995   100    18  4.104276       홍차8
996   100    17  4.164773       홍차7
997   100    14  4.026915       홍차4
998   100     4  0.838720       커피4
999   100     7  1.094826       커피7

[1000 rows x 4 columns]

-

### user-item matrix

`-` 아래와 같은 매트릭스를 고려하자.

In [341]:
df2=pd.DataFrame([[None]*20]*100,columns=['커피'+str(i+1) for i in range(10)]+['홍차'+str(i+1) for i in range(10)])
df2.index=pd.Index(['user'+str(i) for i in range(1,101)])
df2

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
user96,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user97,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user98,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user99,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user100,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

`-` 이러한 형식의 매트릭스에 df의 정보를 채워넣자.

In [342]:
for (i,j) in zip(df.user.to_list(), df.item.to_list()):
    df2.iloc[i-1,j-1]=df.query('user == @i and item == @j')['rating'].to_list()[0]

In [343]:
df2.index=pd.Index(['user'+str(i) for i in range(1,101)])

In [344]:
df2.iloc[:5]

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user1,None,None,None,3.935039,3.713112,3.922179,4.165764,4.226724,None,None,0.959677,None,None,0.787547,None,None,None,None,None,None
user2,3.909745,4.11717,None,None,None,3.808519,None,None,3.963164,None,None,None,None,None,1.06571,None,None,0.918659,1.163262,None
user3,None,3.787083,4.041364,None,4.224596,None,None,None,3.816186,4.115778,1.073658,None,None,1.093765,None,1.065215,None,None,None,None
user4,None,None,None,3.757238,4.268842,3.913475,None,None,None,None,0.836371,None,1.174135,None,None,None,None,None,1.153179,3.726432
user5,None,None,None,3.555718,3.826683,None,3.820999,3.50051,4.011156,None,None,1.124607,1.156935,None,None,None,0.81715,None,0.867264,None

- user1 $\sim$ user5는 대체로 커피를 선호한다. 
- user1은 커피1,2,3,5,9,10을 먹지 않았는데 아마 먹는다면 높은 점수를 줄 것이다. 
- 반대로 먹어보지 않은 홍차종류에는 낮은 점수를 줄 것이다.

In [345]:
df2.iloc[47:53]

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user48,4.018805,None,None,None,None,None,None,4.018385,4.264931,None,1.196839,None,1.066406,1.270823,None,None,None,0.942779,1.214148,None
user49,4.379461,3.902307,4.101265,4.29727,4.178992,4.092554,None,None,None,None,0.966461,None,0.916446,None,None,None,None,None,None,4.085241
user50,None,4.382008,4.2637,None,3.849102,None,3.69737,None,None,None,None,None,0.92486,None,1.152978,None,None,1.009617,None,None
user51,None,0.694796,1.164011,None,0.964617,None,1.391295,1.0149,None,0.838785,None,None,None,None,None,None,None,3.856604,None,1.067545
user52,None,0.989442,0.961105,None,0.969555,None,None,None,None,None,None,3.488142,None,3.584484,3.819045,None,4.286833,None,None,1.085524
user53,None,0.998253,1.032884,0.674988,None,None,0.998516,None,1.101346,None,3.989613,None,None,None,3.994189,None,None,4.02982,4.040601,None

- user1 $\sim$ user50은 커피를 선호하고 user51 $\sim$ user100은 홍차를 선호함

In [346]:
df2.iloc[94:]

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user95,None,1.14804,None,None,None,None,0.888305,1.064191,None,1.376328,4.031612,None,None,3.998592,None,None,None,4.055125,3.998839,None
user96,0.942084,None,None,None,None,None,None,None,None,None,None,4.125248,4.109143,None,None,4.215392,3.762246,4.1423,None,0.827988
user97,None,0.73649,None,None,None,0.814217,1.420604,1.050803,None,None,3.827543,None,4.055171,None,None,None,4.009129,4.063267,None,0.597993
user98,None,None,0.76752,None,1.072218,None,None,1.021994,0.844369,1.117812,3.814472,None,None,None,4.095386,4.159027,None,None,None,1.194373
user99,None,None,None,1.45157,None,0.794026,None,1.296687,0.755774,1.076408,None,3.822382,4.033721,None,3.80931,None,None,None,4.104406,None
user100,0.788717,None,1.149897,None,1.096143,1.083683,None,0.716445,None,None,None,3.844,3.611726,None,3.598425,4.04773,None,None,None,None

### 예측?

`-` None의 값을 추론하는 방법? 머리속으로는 이미 알고있음. 그런데 어떻게 수식화 할 수 있을 것인지?

In [351]:
df2.loc['user1']

커피1         None
커피2         None
커피3         None
커피4     3.935039
커피5     3.713112
커피6     3.922179
커피7     4.165764
커피8     4.226724
커피9         None
커피10        None
홍차1     0.959677
홍차2         None
홍차3         None
홍차4     0.787547
홍차5         None
홍차6         None
홍차7         None
홍차8         None
홍차9         None
홍차10        None
Name: user1, dtype: object

`-` 유저의 취향은 예를들면 아래와 같이 표현할 수 있다. 
- user1의 취향 = (커피좋아함, 홍차싫어함) = (0.9,0.21)

`-` 숫자로 나타내면 아래와 같다.

In [394]:
user1_prprnc = (0.8, 0.21) 
user1_prprnc

(0.8, 0.21)

`-` 여기에서 (0.8, 0.21)은 각각 (커피음료, 홍차음료)로 해석할 수 있다. 현재는 단순하게 원소가 2인 벡터이지만 다양한 아이템의 경우 아래와 같은 featrue도 가능하다. 
- 음료의특징: (커피음료, 홍차음료, 우유포함, 설탕포함정도, 아이스여부, 행사여부, 이벤트중인음료, ...)

`-` 아이템1과 11의 특징은 예를들면 아래와 같이 표현할 수 있다.

In [435]:
item4_ftr = (0.71, 0.03) # 커피4
item11_ftr = (0.1, 0.88) # 홍차1

`-` 유저의 선호도와 아이템의 feature를 내적해보자.

In [436]:
np.array(user1_prprnc) @ np.array(item4_ftr)

0.574

In [437]:
np.array(user1_prprnc) @ np.array(item11_ftr)

0.256

`-` 유저의 선호도와 item의 feature가 비슷할수록 값이 높게 나온다. 실제 user1이 커피4와 홍차1에 매긴 평점은 (3.935039,0.959677) 인데 이 값이 (0.574,0.256) 와 비슷하게 만들면 된다.

`-` 적당히 값을 조정하여 다시 계산해보자.

In [441]:
user1_prprnc = (0.8, 0.2) 
item4_ftr = (5, -0.5) # 커피4
item11_ftr = (-0.1, 5) # 홍차1

In [442]:
np.array(user1_prprnc) @ np.array(item4_ftr)

3.9

In [443]:
np.array(user1_prprnc) @ np.array(item11_ftr)

0.9199999999999999

- 적당히 이런식으로?...

`-` 따라서 `user1_prprnc`, `item4_ftr`, `item11_ftr`의 값들이 학습을 통하여 조정할 파라메터이다. 확장하면.. 
- `user1_prprnc`, ... , `user100_prprnc`
- `item1_ftr`, ... , `item20_ftr`

을 찾으면 된다.

`-` 신기한것은 이 파라메터들이 있다면 `None`에 대한 추론도 가능하다는 것이다. 예를들어서 user1은 item1를 먹지 않았지만 (즉 커피1) item1_ftr의 `계수값`이 다른유저를 통하여 학습 되었고 그 값이 아래와 같다고 하자.

In [446]:
item1_ftr = (5.8, -0.17)

그러면 커피1에 대하여 user1이 매길것이라 예상되는 평점은 아래와 같다.

In [448]:
np.array(user1_prprnc) @ np.array(item1_ftr)

4.606

`-` 생각해보니까 `user1_prprnc`, ... , `user100_prprnc`, `item1_ftr`, ... , `item20_ftr` 를 ${\bf W}$라고 생각하면 우리가 ${\bf W}$을 바꿈에 따라 예측값과 손실이 결정되므로 네트워크 구조가 만들어진다.

`-` 정리하면 아래와 같은 적당한 매트릭스를 선택하여 

- ${\bf U}=\begin{bmatrix} {\tt user1~prprnc} \\ \dots \\ {\tt user100~prprnc} \end{bmatrix}$ $\quad 100 \times 2$ mat 

- ${\bf V}=\begin{bmatrix} {\tt item1~ftr} \\ \dots \\ {\tt item20~ftr} \end{bmatrix}$ $\quad 20 \times 2$ mat 

${\bf U} {\bf V}^\top \approx$`df2`가 만족하도록 하면 된다.

### fastai를 이용한 학습: df $\to$ dls

In [457]:
dls=CollabDataLoaders.from_df(df,bs=100) # df의 형식: 첫번째열을 사용자인덱스, 두번째열은 아이템인덱스, 세번째열은 rating, 네번째열은 아이템이름으로 약속

In [458]:
dls.items

     user  item    rating item_name
365    46     2  4.046898       커피2
913    58    18  3.936074       홍차8
568    29    20  0.906526      홍차10
735    98    11  1.117812       홍차1
131    85    12  4.174649       홍차2
..    ...   ...       ...       ...
646    16    17  1.110942       홍차7
529    58    16  3.706312       홍차6
521    52    16  3.819045       홍차6
442    19     3  3.980287       커피3
169    56     9  1.256799       커피9

[800 rows x 4 columns]

In [465]:
dls.show_batch()

### fastai를 이용한 학습: learn

In [460]:
lrnr = collab_learner(dls,n_factors=2,y_range=(0,5))
lrnr.fit(30,0.01)

In [461]:
lrnr.show_results()

`-` 학습이 잘 되었다.

### 추천: 마지막유저에 대한 예측결과? (아마 홍차를 좋아하지 않을까?)

In [467]:
dls.show_batch()

In [471]:
x, y = dls.one_batch()

In [472]:
x

tensor([[33,  5],
        [90, 12],
        [92, 17],
        [ 8,  4],
        [86, 18],
        [34,  2],
        [65,  4],
        [24, 17],
        [32, 20],
        [48, 19],
        [39, 13],
        [93, 16],
        [28, 15],
        [93,  3],
        [24,  9],
        [83,  5],
        [41, 16],
        [66, 13],
        [82,  8],
        [ 3,  3],
        [44, 11],
        [66,  1],
        [60,  7],
        [19,  2],
        [34,  6],
        [75,  3],
        [71, 11],
        [91,  8],
        [40,  1],
        [82,  8],
        [27, 20],
        [ 6, 12],
        [ 2, 16],
        [52, 13],
        [ 3, 12],
        [96,  1],
        [97,  7],
        [43,  8],
        [62, 16],
        [ 2,  3],
        [53, 10],
        [18, 13],
        [87, 18],
        [ 3,  4],
        [11, 20],
        [78, 12],
        [97,  8],
        [ 5, 18],
        [55, 19],
        [49,  7],
        [82, 19],
        [89, 18],
        [83,  5],
        [15, 12],
        [71, 19],
        [13,  8],
        [47, 18],
        [77, 17],
        [85, 18],
        [99, 13],
        [71,  3],
        [91, 12],
        [93,  9],
        [32,  4],
        [11,  1],
        [99, 10],
        [ 9,  6],
        [37, 12],
        [39, 15],
        [79, 17],
        [12, 14],
        [17, 20],
        [47,  4],
        [45, 19],
        [28, 14],
        [60, 14],
        [85, 20],
        [32, 12],
        [67,  1],
        [41,  6],
        [70, 13],
        [14, 18],
        [32, 10],
        [54,  1],
        [72, 18],
        [43,  7],
        [48, 14],
        [63, 14],
        [23,  1],
        [34,  1],
        [53,  8],
        [30,  2],
        [81, 13],
        [37, 18],
        [79, 14],
        [72, 18],
        [15,  3],
        [58,  8],
        [72, 17],
        [84,  9]])

In [473]:
y

tensor([[3.8841],
        [4.0740],
        [4.2110],
        [4.1704],
        [3.9240],
        [3.9883],
        [0.9209],
        [0.7886],
        [0.9573],
        [0.9428],
        [1.1037],
        [4.2539],
        [0.8191],
        [0.9185],
        [4.1671],
        [1.3219],
        [1.0192],
        [4.3415],
        [1.0013],
        [3.7871],
        [3.5376],
        [1.3634],
        [0.6438],
        [3.9822],
        [3.9594],
        [1.1096],
        [1.3426],
        [1.4362],
        [3.8607],
        [1.0546],
        [1.3456],
        [0.9856],
        [1.0657],
        [3.4881],
        [1.0737],
        [0.8280],
        [0.8142],
        [4.0391],
        [4.5269],
        [4.0571],
        [1.1013],
        [0.9817],
        [3.7327],
        [4.0414],
        [0.9072],
        [4.0872],
        [1.4206],
        [0.8171],
        [3.9909],
        [4.0926],
        [4.2850],
        [4.1750],
        [0.7048],
        [0.9303],
        [3.7663],
        [4.0675],
        [0.8345],
        [3.9782],
        [4.4613],
        [3.8224],
        [1.1899],
        [4.2099],
        [1.0655],
        [4.0534],
        [4.1945],
        [0.7558],
        [3.7392],
        [0.5562],
        [1.3496],
        [3.8441],
        [0.7485],
        [0.9379],
        [3.9969],
        [0.9476],
        [1.2098],
        [3.7753],
        [3.6889],
        [1.1738],
        [0.7987],
        [3.9163],
        [3.9499],
        [0.8656],
        [3.7496],
        [0.9947],
        [4.2200],
        [4.2249],
        [1.0664],
        [3.9509],
        [4.0336],
        [3.8677],
        [0.9985],
        [3.6951],
        [4.2049],
        [0.7794],
        [3.9599],
        [4.0153],
        [4.0335],
        [0.8225],
        [3.9910],
        [1.0262]])

위와 같은 양식으로 넣어보자.

In [480]:
xx = torch.tensor([[100,i] for i in range(1,21)])

In [481]:
lrnr.model(xx.to("cuda:0"))

tensor([0.9876, 0.9024, 0.9773, 1.0426, 1.0167, 1.0830, 0.9469, 1.0651, 0.9543,
        0.9429, 1.0613, 4.0173, 3.9544, 3.9878, 4.0336, 3.9385, 3.9631, 3.9678,
        4.0884, 3.9306], device='cuda:0', grad_fn=<AddBackward0>)

`-` 예상대로 홍차를 매우 좋아함