In [1]:
from fastai.text.all import *

In [2]:
path = untar_data(URLs.IMDB)

In [3]:
files = get_text_files(path, folders=['train','test','unsup'])
files

(#100000) [Path('/home/cgb3/.fastai/data/imdb/train/neg/7473_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/11965_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/11897_3.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/9582_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/2709_2.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/7593_2.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/3936_2.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/12323_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/576_3.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/12303_1.txt')...]

In [4]:
dls=DataBlock(blocks=TextBlock.from_folder(path,is_lm=True),
              get_items=partial(get_text_files,folders=['train','test','unsup']),
              splitter=RandomSplitter(0.1)).dataloaders(path,path=path, bs=128, seq_len=80)

In [5]:
dls.show_batch()

In [11]:
lrnr = language_model_learner(dls,AWD_LSTM,drop_mult=0.3,metrics=[accuracy,Perplexity()]).to_fp16()

In [12]:
lrnr.fit_one_cycle(5)

In [17]:
TEXT = 'I liked this movie because' 
N_WORDS= 40 
N_SENTENCES = 2 
preds = [lrnr.predict(TEXT,N_WORDS,temperature=0.75) for _ in range(N_SENTENCES)]
print("\n".join(preds))

i liked this movie because it was the best movie he ever had . i liked the story of King Arthur and the personal love that he had with his father , who has even been a boy . This is not
i liked this movie because it was a big disappointment , like other films i hope this is not a major remake . Instead , i would have to try and remember a lot of Yul Brynner roles as the

- 말이 안되는것 같은데 그럴듯해보이긴함