In [37]:
#hide
options(jupyter.plot_scale=3)
options(jupyter.display_mimetypes=c("text/html"))
#options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)

### 볼링공 문제

### 풀이

(풀이1)

In [38]:
a=c(1,3,2,3,2)

In [39]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 16

In [40]:
1:1000/1000

   [1] 0.001 0.002 0.003 0.004 0.005 0.006 0.007 0.008 0.009 0.010 0.011 0.012
  [13] 0.013 0.014 0.015 0.016 0.017 0.018 0.019 0.020 0.021 0.022 0.023 0.024
  [25] 0.025 0.026 0.027 0.028 0.029 0.030 0.031 0.032 0.033 0.034 0.035 0.036
  [37] 0.037 0.038 0.039 0.040 0.041 0.042 0.043 0.044 0.045 0.046 0.047 0.048
  [49] 0.049 0.050 0.051 0.052 0.053 0.054 0.055 0.056 0.057 0.058 0.059 0.060
  [61] 0.061 0.062 0.063 0.064 0.065 0.066 0.067 0.068 0.069 0.070 0.071 0.072
  [73] 0.073 0.074 0.075 0.076 0.077 0.078 0.079 0.080 0.081 0.082 0.083 0.084
  [85] 0.085 0.086 0.087 0.088 0.089 0.090 0.091 0.092 0.093 0.094 0.095 0.096
  [97] 0.097 0.098 0.099 0.100 0.101 0.102 0.103 0.104 0.105 0.106 0.107 0.108
 [109] 0.109 0.110 0.111 0.112 0.113 0.114 0.115 0.116 0.117 0.118 0.119 0.120
 [121] 0.121 0.122 0.123 0.124 0.125 0.126 0.127 0.128 0.129 0.130 0.131 0.132
 [133] 0.133 0.134 0.135 0.136 0.137 0.138 0.139 0.140 0.141 0.142 0.143 0.144
 [145] 0.145 0.146 0.147 0.148 0.149 0.150 0.151 0.152 0.153 0.154 0.155 0.156
 [157] 0.157 0.158 0.159 0.160 0.161 0.162 0.163 0.164 0.165 0.166 0.167 0.168
 [169] 0.169 0.170 0.171 0.172 0.173 0.174 0.175 0.176 0.177 0.178 0.179 0.180
 [181] 0.181 0.182 0.183 0.184 0.185 0.186 0.187 0.188 0.189 0.190 0.191 0.192
 [193] 0.193 0.194 0.195 0.196 0.197 0.198 0.199 0.200 0.201 0.202 0.203 0.204
 [205] 0.205 0.206 0.207 0.208 0.209 0.210 0.211 0.212 0.213 0.214 0.215 0.216
 [217] 0.217 0.218 0.219 0.220 0.221 0.222 0.223 0.224 0.225 0.226 0.227 0.228
 [229] 0.229 0.230 0.231 0.232 0.233 0.234 0.235 0.236 0.237 0.238 0.239 0.240
 [241] 0.241 0.242 0.243 0.244 0.245 0.246 0.247 0.248 0.249 0.250 0.251 0.252
 [253] 0.253 0.254 0.255 0.256 0.257 0.258 0.259 0.260 0.261 0.262 0.263 0.264
 [265] 0.265 0.266 0.267 0.268 0.269 0.270 0.271 0.272 0.273 0.274 0.275 0.276
 [277] 0.277 0.278 0.279 0.280 0.281 0.282 0.283 0.284 0.285 0.286 0.287 0.288
 [289] 0.289 0.290 0.291 0.292 0.293 0.294 0.295 0.296 0.297 0.298 0.299 0.300
 [301] 0.301 0.302 0.303 0.304 0.305 0.306 0.307 0.308 0.309 0.310 0.311 0.312
 [313] 0.313 0.314 0.315 0.316 0.317 0.318 0.319 0.320 0.321 0.322 0.323 0.324
 [325] 0.325 0.326 0.327 0.328 0.329 0.330 0.331 0.332 0.333 0.334 0.335 0.336
 [337] 0.337 0.338 0.339 0.340 0.341 0.342 0.343 0.344 0.345 0.346 0.347 0.348
 [349] 0.349 0.350 0.351 0.352 0.353 0.354 0.355 0.356 0.357 0.358 0.359 0.360
 [361] 0.361 0.362 0.363 0.364 0.365 0.366 0.367 0.368 0.369 0.370 0.371 0.372
 [373] 0.373 0.374 0.375 0.376 0.377 0.378 0.379 0.380 0.381 0.382 0.383 0.384
 [385] 0.385 0.386 0.387 0.388 0.389 0.390 0.391 0.392 0.393 0.394 0.395 0.396
 [397] 0.397 0.398 0.399 0.400 0.401 0.402 0.403 0.404 0.405 0.406 0.407 0.408
 [409] 0.409 0.410 0.411 0.412 0.413 0.414 0.415 0.416 0.417 0.418 0.419 0.420
 [421] 0.421 0.422 0.423 0.424 0.425 0.426 0.427 0.428 0.429 0.430 0.431 0.432
 [433] 0.433 0.434 0.435 0.436 0.437 0.438 0.439 0.440 0.441 0.442 0.443 0.444
 [445] 0.445 0.446 0.447 0.448 0.449 0.450 0.451 0.452 0.453 0.454 0.455 0.456
 [457] 0.457 0.458 0.459 0.460 0.461 0.462 0.463 0.464 0.465 0.466 0.467 0.468
 [469] 0.469 0.470 0.471 0.472 0.473 0.474 0.475 0.476 0.477 0.478 0.479 0.480
 [481] 0.481 0.482 0.483 0.484 0.485 0.486 0.487 0.488 0.489 0.490 0.491 0.492
 [493] 0.493 0.494 0.495 0.496 0.497 0.498 0.499 0.500 0.501 0.502 0.503 0.504
 [505] 0.505 0.506 0.507 0.508 0.509 0.510 0.511 0.512 0.513 0.514 0.515 0.516
 [517] 0.517 0.518 0.519 0.520 0.521 0.522 0.523 0.524 0.525 0.526 0.527 0.528
 [529] 0.529 0.530 0.531 0.532 0.533 0.534 0.535 0.536 0.537 0.538 0.539 0.540
 [541] 0.541 0.542 0.543 0.544 0.545 0.546 0.547 0.548 0.549 0.550 0.551 0.552
 [553] 0.553 0.554 0.555 0.556 0.557 0.558 0.559 0.560 0.561 0.562 0.563 0.564
 [565] 0.565 0.566 0.567 0.568 0.569 0.570 0.571 0.572 0.573 0.574 0.575 0.576
 [577] 0.577 0.578 0.579 0.580 0.581 0.582 0.583 0.584 0.585 0.586 0.587 0.588
 [589] 0.589 0.590 0.591 0.592 0.593 0.594 0.595 0.596 0.597 0.598 0.599 0.600
 [601] 0.601 0.602 0.603 0.604 0.605 0.606 0.607 0.608 0.609 0.610 0.611 0.612
 [613] 0.613 0.614 0.615 0.616 0.617 0.618 0.619 0.620 0.621 0.622 0.623 0.624
 [625] 0.625 0.626 0.627 0.628 0.629 0.630 0.631 0.632 0.633 0.634 0.635 0.636
 [637] 0.637 0.638 0.639 0.640 0.641 0.642 0.643 0.644 0.645 0.646 0.647 0.648
 [649] 0.649 0.650 0.651 0.652 0.653 0.654 0.655 0.656 0.657 0.658 0.659 0.660
 [661] 0.661 0.662 0.663 0.664 0.665 0.666 0.667 0.668 0.669 0.670 0.671 0.672
 [673] 0.673 0.674 0.675 0.676 0.677 0.678 0.679 0.680 0.681 0.682 0.683 0.684
 [685] 0.685 0.686 0.687 0.688 0.689 0.690 0.691 0.692 0.693 0.694 0.695 0.696
 [697] 0.697 0.698 0.699 0.700 0.701 0.702 0.703 0.704 0.705 0.706 0.707 0.708
 [709] 0.709 0.710 0.711 0.712 0.713 0.714 0.715 0.716 0.717 0.718 0.719 0.720
 [721] 0.721 0.722 0.723 0.724 0.725 0.726 0.727 0.728 0.729 0.730 0.731 0.732
 [733] 0.733 0.734 0.735 0.736 0.737 0.738 0.739 0.740 0.741 0.742 0.743 0.744
 [745] 0.745 0.746 0.747 0.748 0.749 0.750 0.751 0.752 0.753 0.754 0.755 0.756
 [757] 0.757 0.758 0.759 0.760 0.761 0.762 0.763 0.764 0.765 0.766 0.767 0.768
 [769] 0.769 0.770 0.771 0.772 0.773 0.774 0.775 0.776 0.777 0.778 0.779 0.780
 [781] 0.781 0.782 0.783 0.784 0.785 0.786 0.787 0.788 0.789 0.790 0.791 0.792
 [793] 0.793 0.794 0.795 0.796 0.797 0.798 0.799 0.800 0.801 0.802 0.803 0.804
 [805] 0.805 0.806 0.807 0.808 0.809 0.810 0.811 0.812 0.813 0.814 0.815 0.816
 [817] 0.817 0.818 0.819 0.820 0.821 0.822 0.823 0.824 0.825 0.826 0.827 0.828
 [829] 0.829 0.830 0.831 0.832 0.833 0.834 0.835 0.836 0.837 0.838 0.839 0.840
 [841] 0.841 0.842 0.843 0.844 0.845 0.846 0.847 0.848 0.849 0.850 0.851 0.852
 [853] 0.853 0.854 0.855 0.856 0.857 0.858 0.859 0.860 0.861 0.862 0.863 0.864
 [865] 0.865 0.866 0.867 0.868 0.869 0.870 0.871 0.872 0.873 0.874 0.875 0.876
 [877] 0.877 0.878 0.879 0.880 0.881 0.882 0.883 0.884 0.885 0.886 0.887 0.888
 [889] 0.889 0.890 0.891 0.892 0.893 0.894 0.895 0.896 0.897 0.898 0.899 0.900
 [901] 0.901 0.902 0.903 0.904 0.905 0.906 0.907 0.908 0.909 0.910 0.911 0.912
 [913] 0.913 0.914 0.915 0.916 0.917 0.918 0.919 0.920 0.921 0.922 0.923 0.924
 [925] 0.925 0.926 0.927 0.928 0.929 0.930 0.931 0.932 0.933 0.934 0.935 0.936
 [937] 0.937 0.938 0.939 0.940 0.941 0.942 0.943 0.944 0.945 0.946 0.947 0.948
 [949] 0.949 0.950 0.951 0.952 0.953 0.954 0.955 0.956 0.957 0.958 0.959 0.960
 [961] 0.961 0.962 0.963 0.964 0.965 0.966 0.967 0.968 0.969 0.970 0.971 0.972
 [973] 0.973 0.974 0.975 0.976 0.977 0.978 0.979 0.980 0.981 0.982 0.983 0.984
 [985] 0.985 0.986 0.987 0.988 0.989 0.990 0.991 0.992 0.993 0.994 0.995 0.996
 [997] 0.997 0.998 0.999 1.000

- ? 중복이 계산되어서 이상한 값이 나왔다..

`-` 아래와 같이 수정하면 된다.

In [23]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if ((a[i]!=a[j])&(i>j)) count=count+1
    }
}
count

[1] 8

`-` 아예 아래처럼 해도 괜찮다.

In [24]:
count=0
for (i in 1:5){
    for (j in i:5){
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 8

(풀이2)

In [25]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
A

      [,1] [,2]
 [1,] 0    0
 [2,] 0    0
 [3,] 0    0
 [4,] 0    0
 [5,] 0    0
 [6,] 0    0
 [7,] 0    0
 [8,] 0    0
 [9,] 0    0
[10,] 0    0
[11,] 0    0
[12,] 0    0
[13,] 0    0
[14,] 0    0
[15,] 0    0
[16,] 0    0
[17,] 0    0
[18,] 0    0
[19,] 0    0
[20,] 0    0
[21,] 0    0
[22,] 0    0
[23,] 0    0
[24,] 0    0
[25,] 0    0

In [26]:
count=0
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1
 [2,] 1    3
 [3,] 1    2
 [4,] 1    3
 [5,] 1    2
 [6,] 3    1
 [7,] 3    3
 [8,] 3    2
 [9,] 3    3
[10,] 3    2
[11,] 2    1
[12,] 2    3
[13,] 2    2
[14,] 2    3
[15,] 2    2
[16,] 3    1
[17,] 3    3
[18,] 3    2
[19,] 3    3
[20,] 3    2
[21,] 2    1
[22,] 2    3
[23,] 2    2
[24,] 2    3
[25,] 2    2

In [27]:
vec1<-c()
vec2<-c()
for(i in 1:25){
    vec1[i]<- A[i,1]-A[i,2]
    vec2[i]<- A[i,1]>A[i,2]
}

In [28]:
vec1

 [1]  0 -2 -1 -2 -1  2  0  1  0  1  1 -1  0 -1  0  2  0  1  0  1  1 -1  0 -1  0

In [9]:
vec2

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [10]:
(vec1!=0) & (vec2==TRUE)

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [11]:
sum((vec1!=0) & (vec2==TRUE))

[1] 8

`-` 그래도 위의 코드보다 디버깅하기에는 좋음

`-` 빠르고 간단하고 효율적인 코드도 중요한데 틀리지 않는것이 가장 중요함

`-` 특히 삼성문제의 경우 예외사항을 잘 처리해야하는 문제가 주로 출제된다.

`-` 시간이 많다면 2개 이상으로 구현하고 결과를 맞춰보는것도 좋음.

(풀이3)

In [12]:
A=expand.grid(a,a)
A

   Var1 Var2
1  1    1
2  3    1
3  2    1
4  3    1
5  2    1
6  1    3
7  3    3
8  2    3
9  3    3
10 2    3
11 1    2
12 3    2
13 2    2
14 3    2
15 2    2
16 1    3
17 3    3
18 2    3
19 3    3
20 2    3
21 1    2
22 3    2
23 2    2
24 3    2
25 2    2

In [13]:
A %>% mutate(C=Var1-Var2)

ERROR: Error in A %>% mutate(C = Var1 - Var2): could not find function "%>%"

In [14]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0)

ERROR: Error in A %>% mutate(C = Var1 - Var2) %>% filter(C > 0): could not find function "%>%"

In [15]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count

ERROR: Error in A %>% mutate(C = Var1 - Var2) %>% filter(C > 0) %>% count: could not find function "%>%"

In [16]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count %>% as.numeric

ERROR: Error in A %>% mutate(C = Var1 - Var2) %>% filter(C > 0) %>% count %>% : could not find function "%>%"

(풀이4)

In [17]:
A=outer(a,a)

In [18]:
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2
[2,] 3    9    6    9    6
[3,] 2    6    4    6    4
[4,] 3    9    6    9    6
[5,] 2    6    4    6    4

In [19]:
sum(!(A[upper.tri(A)] %in% c(1,4,9)))

[1] 8