# (노트) 기울기소멸, 추천시스템 (홍차커피)

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [빅데이터분석]

## 기울기소멸

### 고요속의 외침

`-` https://www.youtube.com/watch?v=ouitOnaDtFY

`-` 중간에 한명이라도 잘못말한다면..

### 정의

`-` In machine learning, the vanishing gradient problem is encountered when training artificial neural networks with gradient-based learning methods and backpropagation.

### 이해

`-` 당연한거 아닌가? 
- 그래디언트 기반의 학습(그래디언트 기반의 옵티마이저): 손실함수의 기울기를 통하여 업데이트 하는 방식
- 역전파: 손실함수의 기울기를 구하는 테크닉(체인룰 + $\alpha$). 구체적으로는 (1) 손실함수를 여러단계로 쪼개고 (2) 각 단계의 미분을 각각 구하고 (3) 그것들을 모두 곱하여 기울기를 계산한다. 
- 0근처의 숫자를 계속 곱하면 터지거나 0으로 간다. (사실 안정적인 기울기가 나올거라고 보는것이 이상한것임)

In [206]:
import numpy as np

In [207]:
grads = np.random.uniform(low=-2,high=2,size=100)
grads

array([ 0.18688288,  0.43450847, -0.87513215,  1.35976661, -1.67602921,
       -1.94881797,  0.28000878, -0.07982773,  0.41098101,  1.44913431,
        1.42155413,  0.30179395, -1.11750978, -1.03629995,  1.73194045,
        1.30429018, -1.85441508, -0.23849127,  1.69550035,  1.08930237,
        0.61166949, -1.55165233,  1.35400582, -0.79701747,  0.80542101,
       -1.63942602,  1.5169811 , -0.99256516,  1.12927938, -0.60001878,
       -0.79629782, -1.41639694, -1.60737528, -0.810134  ,  1.46868468,
        0.80995697, -0.01861418,  1.870188  ,  0.7237886 ,  1.94490223,
        0.30018531,  0.7239008 , -1.49830624,  0.35257188,  1.54092802,
        0.37818125,  1.85990611, -1.03105941,  0.5865016 , -1.98180695,
       -0.27474677,  0.88501944,  0.47957049,  1.97015467,  1.18178691,
        1.35343833,  1.84192922, -0.16687519, -0.63599077,  1.78165492,
       -1.38607268, -0.6363796 ,  1.26337952, -1.82063191,  1.92715124,
        0.56908745, -1.44857969, -0.44694881,  1.12397453,  0.81900019,
       -1.34730467, -0.03100787, -1.98911877,  1.26495344,  0.4073905 ,
       -1.96826953,  1.93068033,  1.07119525, -0.05285845,  1.43202408,
        0.10627962, -1.24520154,  1.28336267,  1.24564003,  0.45895504,
        0.05938386, -0.33004816,  1.71594089, -1.92451146, -1.67093832,
        1.64631833, -0.55316687,  0.43782105, -1.87975355, -1.89361645,
       -0.06089341,  0.571681  , -0.39305498, -1.40057471, -0.97509085])

In [208]:
grads.prod()

-4.231809904440714e-11

- 기울기가 소멸함

In [209]:
grads = np.random.uniform(low=-3,high=3,size=100)
grads.prod()

16676775121011.598

- 기울기가 폭발함

In [210]:
grads = np.random.uniform(low=-3,high=3,size=100)
grads.prod()

-504691.96433542186

In [244]:
grads = np.random.uniform(low=-1,high=3.5,size=100)
grads.prod()

-5.898185033226975e-06

`-` 도깨비: 기울기가 소멸하기도 하고 터지기도 한다.

### 해결책 (기울기 소멸에 대한 해결책)

> Note: 잘 정리되어있는게 없어서 제 머리속에서 정리했습니다. 부정확할수 있어요.

`-` 개념 
- 데이터 $\to$ (아키텍처, 손실함수, 역전파, 업데이트)

`-` Multi-level hierarchy 
- 여러층을 쪼개서 학습하자 $\to$ 어떻게?... 사전학습, 층별학습. 
- 기울기소실문제를 해결하여 딥러닝을 유행시킨 태초의 방법임. 
- 입력자료의 전처리도 여기에 해당함 
- 결국 입력자료를 바꾼뒤에 학습하는 형태

`-` Faster hardware 
- GPU를 중심으로 한 테크닉. 
- 근본적인 문제해결은 아니라는 힌튼의 비판. 
- CPU를 쓸때보다 GPU를 쓰면 약간 더 깊은 모형을 학습할 수 있다 정도?

`-` ResNet 
- 훌륭한 접근법중 하나임 
- 아키텍처를 변경하는 방법이지만, 사실상 손실함수를 스무딩 시켜버리는 기법으로 이해해도 된다. 
- 숏컷이라는 아키텍처를 추가하여 이리저리 실험해보니까 손실함수가 스무딩 되었다! <-- 이런게 아니라.. 
- 손실함수를 스무딩하기 위해서는 층별의 차이(residual)만 학습하는게 유리할것 같다. 그런데 그것을 위한 효과를 주기 위해 아키텍처를 설계하려면 단지 숏컷을 만들기만 하면 된다. <-- 이런 모티브였을 것이다..

`-` 활성화함수의 변경 
- 렐루의 개발 $\to$ 특정노드가 죽음 $\to$ 리키렐루의 개발

`-` 배치정규화 
- 어쩌다보니 되는 것. 
- 배치정규화는 공변량 쉬프트를 잡기위한 방법임. 그런데 기울기소멸에도 효과가 있음. 현재는 기울기 소멸에 대한 해결책으로 빠짐없이 언급되는 내용. 하지만 2015년의 원래 논문에서는 기울기소멸에 대한 언급없음 (https://arxiv.org/pdf/1502.03167.pdf)
- 심지어 배치정규화는 오버피팅을 잡는것에도 효과가 있음 (이것은 논문에 언급있음)

`-` **기울기를 안구하면 안되나?**
- 베이지안 최적화기법: (https://arxiv.org/pdf/1807.02811.pdf) $\to$ GPU를 어떻게써? $\to$ 진짜 엄청느려요.. 지옥입니다.. 
- 강화학습?

## 딥러닝 + 머신러닝 공부를 위한 교재

`-` 기계학습, 오일석 (http://www.yes24.com/Product/Goods/57537091) 
- 좋은 교재에요.. 
- 딥러닝 초급내용을 커버할 수 있습니다..

`-` 심층학습, 이안굿펠로우 (https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=171345378) 
- 이안굿펠로우는 GAN을 만든사람입니다. 
- 거의 표준임. 
- 번역상태가 너무 너무 안좋아요.

`-` 머신러닝교재들 
- 패턴인식: 
- Element of Statistical Learning

## 추천시스템

### import

In [2]:
import torch 
import matplotlib.pyplot as plt

In [3]:
from fastai.collab import * 
from fastai.tabular.all import *

### data (시뮬레이션)

In [4]:
user = list(range(1,101))
item = list(range(1,21))
_lst = [[0,0,4.2]]

In [5]:
def f(u,i): 
    if u<=50 and i<=10: 
        return np.random.randn(1)[0]*0.2+4 
    elif u<=50 and i>10:
        return np.random.randn(1)[0]*0.2+1 
    elif u>50 and i<=10:
        return np.random.randn(1)[0]*0.2+1 
    elif u>50 and i>10:
        return np.random.randn(1)[0]*0.2+4 
        
for u in user:
    _item = np.random.choice(list(range(1,21)),size=10,replace=False).tolist()
    for i in _item:
        _lst.append([u,i,f(u,i)])

In [6]:
_df1=pd.DataFrame(_lst[1:],columns=['user','item','rating'])
_df1

     user  item    rating
0       1     2  4.037978
1       1    18  0.827490
2       1     6  3.995262
3       1     1  3.910677
4       1     5  3.948963
..    ...   ...       ...
995   100    11  3.751929
996   100    13  3.821574
997   100    12  3.907669
998   100    19  4.370632
999   100     6  0.679340

[1000 rows x 3 columns]

In [7]:
['커피'+str(i+1) for i in range(10)]+['홍차'+str(i+1) for i in range(10)]

['커피1',
 '커피2',
 '커피3',
 '커피4',
 '커피5',
 '커피6',
 '커피7',
 '커피8',
 '커피9',
 '커피10',
 '홍차1',
 '홍차2',
 '홍차3',
 '홍차4',
 '홍차5',
 '홍차6',
 '홍차7',
 '홍차8',
 '홍차9',
 '홍차10']

In [8]:
_df2 = pd.DataFrame({'item':list(range(1,21)), 'item_name':['커피'+str(i+1) for i in range(10)]+['홍차'+str(i+1) for i in range(10)]})
_df2

    item item_name
0      1       커피1
1      2       커피2
2      3       커피3
3      4       커피4
4      5       커피5
5      6       커피6
6      7       커피7
7      8       커피8
8      9       커피9
9     10      커피10
10    11       홍차1
11    12       홍차2
12    13       홍차3
13    14       홍차4
14    15       홍차5
15    16       홍차6
16    17       홍차7
17    18       홍차8
18    19       홍차9
19    20      홍차10

In [9]:
df= _df1.merge(_df2).sort_values('user') 
df

     user  item    rating item_name
0       1     2  4.037978       커피2
262     1    10  3.938256      커피10
104     1     6  3.995262       커피6
362     1    14  1.230001       홍차4
316     1    17  1.058811       홍차7
..    ...   ...       ...       ...
857   100    12  3.907669       홍차2
261   100     5  0.831061       커피5
48    100     2  0.913255       커피2
809   100     9  0.935179       커피9
999   100    19  4.370632       홍차9

[1000 rows x 4 columns]

In [10]:
df.to_csv('2021-11-30-recommend.csv',index=False)

### data (load)

`-` 가짜 자료

In [11]:
pd.read_csv("2021-11-30-recommend.csv")

     user  item    rating item_name
0       1     2  4.037978       커피2
1       1    10  3.938256      커피10
2       1     6  3.995262       커피6
3       1    14  1.230001       홍차4
4       1    17  1.058811       홍차7
..    ...   ...       ...       ...
995   100    12  3.907669       홍차2
996   100     5  0.831061       커피5
997   100     2  0.913255       커피2
998   100     9  0.935179       커피9
999   100    19  4.370632       홍차9

[1000 rows x 4 columns]

### user-item matrix

`-` 아래와 같은 매트릭스를 고려하자.

In [12]:
df2=pd.DataFrame([[None]*20]*100,columns=['커피'+str(i+1) for i in range(10)]+['홍차'+str(i+1) for i in range(10)])
df2.index=pd.Index(['user'+str(i) for i in range(1,101)])
df2

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user2,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
user96,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user97,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user98,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user99,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
user100,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

`-` 이러한 형식의 매트릭스에 df의 정보를 채워넣자.

In [13]:
for (i,j) in zip(df.user.to_list(), df.item.to_list()):
    df2.iloc[i-1,j-1]=df.query('user == @i and item == @j')['rating'].to_list()[0]

In [14]:
df2.index=pd.Index(['user'+str(i) for i in range(1,101)])

In [15]:
df2.iloc[:5]

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user1,3.910677,4.037978,None,None,3.948963,3.995262,None,4.346887,None,3.938256,None,None,None,1.230001,None,0.862774,1.058811,0.82749,None,None
user2,3.933136,3.940997,3.83004,None,4.306725,None,None,4.057412,None,None,0.826063,None,0.904857,None,None,None,0.837509,1.019619,None,0.681023
user3,3.987507,None,None,None,None,4.098394,None,None,4.080266,3.737265,0.924324,1.259526,None,None,0.878401,1.054966,0.865548,None,None,1.151545
user4,4.10715,4.051205,None,3.92157,None,None,4.107903,3.843773,4.189522,None,0.766275,None,0.781752,None,None,1.154691,None,None,None,1.018237
user5,3.967537,3.736425,None,3.831369,3.936972,None,None,None,4.253454,4.092332,None,1.054604,None,1.127845,0.941917,None,None,None,None,0.914252

- user1 $\sim$ user5는 대체로 커피를 선호한다. 
- user1은 커피1,2,3,5,9,10을 먹지 않았는데 아마 먹는다면 높은 점수를 줄 것이다. 
- 반대로 먹어보지 않은 홍차종류에는 낮은 점수를 줄 것이다.

In [16]:
df2.iloc[47:53]

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user48,3.875466,3.740709,4.188726,4.237465,None,3.893848,None,None,3.984086,None,0.559013,None,None,None,None,0.792111,None,0.811608,0.989279,None
user49,3.890501,4.054751,None,None,None,3.496048,None,None,None,3.707083,1.080992,None,None,1.260421,1.172169,None,None,0.839158,1.112066,0.94168
user50,4.06425,3.803101,None,None,None,4.038332,4.361113,4.114008,None,None,None,None,None,1.111486,None,0.826686,None,0.965161,1.165896,0.895684
user51,0.997594,None,None,0.885554,1.107802,0.859223,0.894022,None,None,0.749077,None,3.795299,None,None,3.83568,None,None,4.054222,3.832147,None
user52,None,1.086465,None,None,0.594889,None,None,1.237119,None,None,4.020981,4.151935,4.211201,3.828047,4.030043,3.876521,None,3.934299,None,None
user53,0.601432,None,None,1.034146,1.149157,0.637791,None,None,0.934743,1.285847,3.752162,3.7758,None,None,None,None,None,None,3.741679,4.51043

- user1 $\sim$ user50은 커피를 선호하고 user51 $\sim$ user100은 홍차를 선호함

In [17]:
df2.iloc[94:]

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
user95,0.938105,1.255787,1.112694,None,None,None,None,None,None,1.117088,4.165253,None,3.934524,3.867645,3.64584,4.135711,None,None,None,3.976326
user96,None,0.843545,1.306823,None,None,0.885346,1.216092,None,None,0.96673,4.017698,3.868443,None,3.890151,None,None,None,3.746795,3.789416,None
user97,None,None,1.324731,None,None,None,None,0.982339,None,None,3.95133,4.058704,3.799767,4.026921,None,3.938614,3.958418,None,3.733993,3.936615
user98,None,0.838123,None,None,1.29585,None,1.241315,0.817806,1.175376,None,4.017887,None,None,3.962631,None,4.18153,4.158003,None,None,3.954295
user99,0.971139,1.051906,None,None,0.908293,None,1.252992,None,None,1.021635,None,4.094337,None,4.112067,3.837316,None,None,3.931823,3.851077,None
user100,None,0.913255,None,None,0.831061,0.67934,None,0.808547,0.935179,None,3.751929,3.907669,3.821574,None,4.030094,None,None,None,4.370632,None

### 예측?

`-` None의 값을 추론하는 방법? 머리속으로는 이미 알고있음. 그런데 어떻게 수식화 할 수 있을 것인지?

In [18]:
df2.loc['user1']

커피1     3.910677
커피2     4.037978
커피3         None
커피4         None
커피5     3.948963
커피6     3.995262
커피7         None
커피8     4.346887
커피9         None
커피10    3.938256
홍차1         None
홍차2         None
홍차3         None
홍차4     1.230001
홍차5         None
홍차6     0.862774
홍차7     1.058811
홍차8      0.82749
홍차9         None
홍차10        None
Name: user1, dtype: object

`-` 유저의 취향은 예를들면 아래와 같이 표현할 수 있다. 
- user1의 취향 = (커피좋아함, 홍차싫어함) = (0.9,0.21)

`-` 숫자로 나타내면 아래와 같다.

In [19]:
user1_prprnc = (0.8, 0.21) 
user1_prprnc

(0.8, 0.21)

`-` 여기에서 (0.8, 0.21)은 각각 (커피음료, 홍차음료)로 해석할 수 있다. 현재는 단순하게 원소가 2인 벡터이지만 다양한 아이템의 경우 아래와 같은 featrue도 가능하다. 
- 음료의특징: (커피음료, 홍차음료, 우유포함, 설탕포함정도, 아이스여부, 행사여부, 이벤트중인음료, ...)

`-` 아이템1과 11의 특징은 예를들면 아래와 같이 표현할 수 있다.

In [20]:
item4_ftr = (0.71, 0.03) # 커피4
item11_ftr = (0.1, 0.88) # 홍차1

`-` 유저의 선호도와 아이템의 feature를 내적해보자.

In [21]:
np.array(user1_prprnc) @ np.array(item4_ftr)

0.5742999999999999

In [22]:
np.array(user1_prprnc) @ np.array(item11_ftr)

0.26480000000000004

`-` 유저의 선호도와 item의 feature가 비슷할수록 값이 높게 나온다. 실제 user1이 커피4와 홍차1에 매긴 평점은 (3.935039,0.959677) 인데 이 값이 (0.574,0.256) 와 비슷하게 만들면 된다.

`-` 적당히 값을 조정하여 다시 계산해보자.

In [23]:
user1_prprnc = (0.8, 0.2) 
item4_ftr = (5, -0.5) # 커피4
item11_ftr = (-0.1, 5) # 홍차1

In [24]:
np.array(user1_prprnc) @ np.array(item4_ftr)

3.9

In [25]:
np.array(user1_prprnc) @ np.array(item11_ftr)

0.9199999999999999

- 적당히 이런식으로?...

`-` 따라서 `user1_prprnc`, `item4_ftr`, `item11_ftr`의 값들이 학습을 통하여 조정할 파라메터이다. 확장하면.. 
- `user1_prprnc`, ... , `user100_prprnc`
- `item1_ftr`, ... , `item20_ftr`

을 찾으면 된다.

`-` 신기한것은 이 파라메터들이 있다면 `None`에 대한 추론도 가능하다는 것이다. 예를들어서 user1은 item1를 먹지 않았지만 (즉 커피1) item1_ftr의 `계수값`이 다른유저를 통하여 학습 되었고 그 값이 아래와 같다고 하자.

In [26]:
item1_ftr = (5.8, -0.17)

그러면 커피1에 대하여 user1이 매길것이라 예상되는 평점은 아래와 같다.

In [27]:
np.array(user1_prprnc) @ np.array(item1_ftr)

4.606

`-` 생각해보니까 `user1_prprnc`, ... , `user100_prprnc`, `item1_ftr`, ... , `item20_ftr` 를 ${\bf W}$라고 생각하면 우리가 ${\bf W}$을 바꿈에 따라 예측값과 손실이 결정되므로 네트워크 구조가 만들어진다.

`-` 정리하면 아래와 같은 적당한 매트릭스를 선택하여 

- ${\bf U}=\begin{bmatrix} {\tt user1~prprnc} \\ \dots \\ {\tt user100~prprnc} \end{bmatrix}$ $\quad 100 \times 2$ mat 

- ${\bf V}=\begin{bmatrix} {\tt item1~ftr} \\ \dots \\ {\tt item20~ftr} \end{bmatrix}$ $\quad 20 \times 2$ mat 

${\bf U} {\bf V}^\top \approx$`df2`가 만족하도록 하면 된다.

### fastai를 이용한 학습: df $\to$ dls

In [28]:
dls=CollabDataLoaders.from_df(df,bs=100) # df의 형식: 첫번째열을 사용자인덱스, 두번째열은 아이템인덱스, 세번째열은 rating, 네번째열은 아이템이름으로 약속

In [29]:
dls.items

     user  item    rating item_name
503    85    16  3.907806       홍차6
265     6    10  4.222861      커피10
961    39    19  1.085325       홍차9
26     52     2  1.086465       커피2
137    66     6  0.919261       커피6
..    ...   ...       ...       ...
538    62    11  4.069290       홍차1
618    93    13  3.831534       홍차3
985    75    19  3.951121       홍차9
641    42    20  1.062895      홍차10
67     37    18  0.858657       홍차8

[800 rows x 4 columns]

In [30]:
dls.show_batch()

### fastai를 이용한 학습: learn

In [31]:
lrnr = collab_learner(dls,n_factors=2,y_range=(0,5))
lrnr.fit(30,0.01)

In [32]:
lrnr.show_results()

`-` 학습이 잘 되었다.

### 추천: 마지막유저에 대한 예측결과? (아마 홍차를 좋아하지 않을까?)

In [33]:
dls.show_batch()

In [34]:
x, y = dls.one_batch()

In [35]:
x

tensor([[ 13,   7],
        [ 45,  15],
        [ 59,  17],
        [ 54,  14],
        [  1,   8],
        [ 32,  10],
        [ 22,  16],
        [ 92,   7],
        [ 14,   4],
        [ 42,   6],
        [ 89,  13],
        [ 97,  20],
        [ 29,   2],
        [ 69,   7],
        [ 14,  14],
        [100,   6],
        [ 19,   6],
        [ 51,  18],
        [ 70,   2],
        [ 17,  20],
        [ 93,   7],
        [ 46,  10],
        [ 55,  18],
        [ 65,  16],
        [ 16,  13],
        [ 87,  12],
        [ 31,   2],
        [ 42,   7],
        [  9,  10],
        [ 13,  15],
        [ 30,  12],
        [ 91,  14],
        [ 65,   8],
        [ 27,  19],
        [ 39,  19],
        [ 86,  14],
        [ 97,  16],
        [ 44,  18],
        [ 21,   5],
        [ 29,  18],
        [ 33,  17],
        [ 29,  14],
        [ 25,   7],
        [ 68,  18],
        [  6,  15],
        [ 86,  11],
        [ 95,  15],
        [ 28,   4],
        [ 70,  11],
        [ 96,  19],
        [ 33,  13],
        [ 75,   6],
        [ 68,   9],
        [100,   8],
        [ 63,   5],
        [ 41,  13],
        [ 73,   9],
        [ 33,   8],
        [ 42,   2],
        [ 85,   8],
        [ 69,   4],
        [ 97,  13],
        [ 77,  17],
        [  8,   8],
        [ 61,  11],
        [ 77,   1],
        [  1,   6],
        [ 31,  12],
        [ 53,  19],
        [ 57,  12],
        [ 60,   3],
        [ 19,  10],
        [ 14,  17],
        [ 87,  18],
        [ 69,   2],
        [ 55,  13],
        [ 29,  13],
        [ 49,  20],
        [ 13,  20],
        [ 96,  14],
        [ 83,  11],
        [ 67,  10],
        [ 11,   1],
        [ 10,  20],
        [ 14,  13],
        [ 10,  15],
        [ 61,  13],
        [ 82,  13],
        [ 24,  15],
        [ 90,  15],
        [ 10,  11],
        [ 38,  18],
        [ 35,  15],
        [ 51,   1],
        [ 56,  16],
        [  5,  10],
        [ 71,  15],
        [  9,   1],
        [ 92,  13],
        [ 16,  18]])

In [36]:
y

tensor([[3.9836],
        [1.0877],
        [3.9484],
        [3.9159],
        [4.3469],
        [3.8124],
        [1.0715],
        [0.9039],
        [3.8369],
        [4.1649],
        [4.1459],
        [3.9366],
        [4.0177],
        [1.1198],
        [1.0580],
        [0.6793],
        [3.9099],
        [4.0542],
        [0.9419],
        [0.8907],
        [1.3885],
        [4.1993],
        [3.9423],
        [4.3462],
        [0.8287],
        [3.8252],
        [3.9971],
        [3.8213],
        [3.8768],
        [0.7361],
        [1.2585],
        [3.9685],
        [1.0076],
        [1.2957],
        [1.0853],
        [4.0504],
        [3.9386],
        [1.2816],
        [4.0803],
        [1.0393],
        [0.5337],
        [1.2556],
        [4.2126],
        [3.7759],
        [0.8137],
        [3.7660],
        [3.6458],
        [3.9502],
        [3.9028],
        [3.7894],
        [1.3141],
        [1.2421],
        [1.1365],
        [0.8085],
        [0.9791],
        [1.0128],
        [0.7804],
        [4.1560],
        [3.8354],
        [0.8309],
        [0.9875],
        [3.7998],
        [3.9337],
        [4.3407],
        [3.9999],
        [0.9321],
        [3.9953],
        [1.0160],
        [3.7417],
        [4.2746],
        [0.8101],
        [4.1826],
        [0.5913],
        [4.2426],
        [1.3188],
        [4.1715],
        [1.2233],
        [0.9417],
        [0.8813],
        [3.8902],
        [3.9465],
        [0.8603],
        [3.9811],
        [1.1176],
        [0.9871],
        [1.0331],
        [4.1361],
        [3.9907],
        [0.8363],
        [3.7122],
        [0.9370],
        [0.9613],
        [1.3409],
        [0.9976],
        [3.9817],
        [4.0923],
        [4.2779],
        [3.6552],
        [4.5978],
        [1.3135]])

위와 같은 양식으로 넣어보자.

In [37]:
xx = torch.tensor([[100,i] for i in range(1,21)])

In [38]:
lrnr.model(xx.to("cuda:0"))

tensor([0.8534, 0.9190, 0.9951, 0.9100, 0.8599, 0.7953, 0.9294, 0.8100, 0.9210,
        0.8996, 3.9746, 4.0349, 4.0377, 3.9937, 3.9437, 4.0813, 4.0146, 3.9201,
        3.9642, 4.0449], device='cuda:0', grad_fn=<AddBackward0>)

`-` 예상대로 홍차를 매우 좋아함

### 49,50,51,52번 체크

In [60]:
xx = torch.tensor([[49,i] for i in range(1,21)])
lrnr.model(xx.to("cuda:0"))

tensor([3.6473, 3.6329, 3.7392, 3.6414, 3.7761, 3.7189, 3.7698, 3.6808, 3.7407,
        3.6818, 0.9812, 1.1056, 1.1133, 1.0925, 1.0704, 1.0111, 0.9291, 1.0367,
        1.0919, 1.0426], device='cuda:0', grad_fn=<AddBackward0>)

In [61]:
xx = torch.tensor([[50,i] for i in range(1,21)])
lrnr.model(xx.to("cuda:0"))

tensor([4.0462, 4.0278, 4.1117, 4.0375, 4.1551, 4.1125, 4.1428, 4.0793, 4.1195,
        4.0710, 0.9638, 1.0928, 1.1011, 1.0822, 1.0625, 0.9853, 0.9047, 1.0290,
        1.0850, 1.0251], device='cuda:0', grad_fn=<AddBackward0>)

In [62]:
xx = torch.tensor([[51,i] for i in range(1,21)])
lrnr.model(xx.to("cuda:0"))

tensor([0.9100, 0.9763, 1.0562, 0.9682, 0.9207, 0.8527, 0.9905, 0.8669, 0.9814,
        0.9576, 3.8888, 3.9551, 3.9585, 3.9123, 3.8603, 3.9990, 3.9280, 3.8357,
        3.8826, 3.9641], device='cuda:0', grad_fn=<AddBackward0>)

In [63]:
xx = torch.tensor([[52,i] for i in range(1,21)])
lrnr.model(xx.to("cuda:0"))

tensor([0.9612, 1.0313, 1.1144, 1.0216, 0.9699, 0.8995, 1.0447, 0.9148, 1.0352,
        1.0113, 4.0101, 4.0698, 4.0727, 4.0304, 3.9823, 4.1127, 4.0474, 3.9591,
        4.0021, 4.0782], device='cuda:0', grad_fn=<AddBackward0>)