# (노트) 티블

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [R]

In [2]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.1.1     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

### 티블 만드는 방법

`-` 방법1: 선언하여 만들기 (새롭게 정의)

In [3]:
tibble(v1=1:3,v2=c(T,F,T), v3=c("a","b","c"))

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

- 각 열들의 자료형이 모두 달라도 가능 (티블의 매력) 
- 티블의 형태는 매트릭스 같지만 이처럼 다른 자료형이 들어가는 것은 마치 리스트를 연상시킨다.

`-` 방법2: 선언하여 만들기2 (기존에 정의된 벡터등을 활용)

In [31]:
x=1:5
y=c("a","b","c","d","e")
tibble(x,y)

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

`-` 방법3: 벡터를 일단 만들고 티블로 변형

In [32]:
as_tibble(x)

  value
1 1
2 2
3 3
4 4
5 5

`-` 방법4: 매트릭스를 일단 만들고 티블로 변형

In [33]:
as_tibble(cbind(x,y))

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

- 모두 chr로 저장되는 단점이 있음!

`-` 방법5: 리스트에서 생성

In [50]:
as_tibble(list(x=x,y=y))

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

`-` 데이터프레임의 경우도 티블과 비슷하게 만들 수 있다.

In [34]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) # 방법1

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [35]:
data.frame(x,y) # 방법2

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

In [36]:
data.frame(x) # 방법3

  x
1 1
2 2
3 3
4 4
5 5

In [37]:
data.frame(cbind(x,y)) # 방법4

  x y
1 1 a
2 2 b
3 3 c
4 4 d
5 5 e

`-` 데이터프레임과 티블은 서로 호환가능하다.

In [38]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c"))

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [39]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) %>% as_tibble

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [40]:
data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) %>% as_tibble %>% data.frame

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

즉 아래가 가능함

In [41]:
df=data.frame(v1=1:3,v2=c(T,F,T), v3=c("a","b","c")) 
df

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [43]:
df=as_tibble(df)
df

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

In [44]:
df=data.frame(df)
df

  v1 v2    v3
1 1   TRUE a
2 2  FALSE b
3 3   TRUE c

### 원소추출