In [1]:
import pandas as pd

In [2]:
from fastai.text.all import *

In [3]:
df = pd.DataFrame({'text':['h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!']*20000})
df

                                                                text
0      h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
1      h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
2      h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
3      h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
4      h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
...                                                              ...
19995  h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
19996  h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
19997  h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
19998  h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!
19999  h e l l o . h e l l o ! h e l l o ? h e l l o ?? h e l l o !!

[20000 rows x 1 columns]

In [4]:
dls = TextDataLoaders.from_df(df,text_col='text',is_lm=True)

In [5]:
dls.show_batch()

In [6]:
lrnr = language_model_learner(dls,AWD_LSTM,metrics=accuracy)

In [7]:
lrnr.fit(7)

In [8]:
lrnr.predict("h e l", n_words=20)

'h e l l o ? ? h e l l o ! ! ! h e l l o . h'