# (노트) fastai - 아메리카노와 홍차, 추천시스템

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [딥러닝2022]

In [30]:
from fastai.collab import *
import torch
import pandas as pd

In [4]:
df_view= pd.read_csv('https://raw.githubusercontent.com/guebin/DL2022/master/_notebooks/2022-09-08-rcmd_view.csv')

In [5]:
df_view

,커피1,커피2,커피3,커피4,커피5,커피6,커피7,커피8,커피9,커피10,홍차1,홍차2,홍차3,홍차4,홍차5,홍차6,홍차7,홍차8,홍차9,홍차10
0,4.149209,NaN,NaN,4.078139,4.033415,4.071871,NaN,NaN,NaN,NaN,1.142659,1.109452,NaN,0.603118,1.084308,NaN,0.906524,NaN,NaN,0.903826
1,4.031811,NaN,NaN,3.822704,NaN,NaN,NaN,4.071410,3.996206,NaN,NaN,0.839565,1.011315,NaN,1.120552,0.911340,NaN,0.860954,0.871482,NaN
2,4.082178,4.196436,NaN,3.956876,NaN,NaN,NaN,4.450931,3.972090,NaN,NaN,NaN,NaN,0.983838,NaN,0.918576,1.206796,0.913116,NaN,0.956194
3,NaN,4.000621,3.895570,NaN,3.838781,3.967183,NaN,NaN,NaN,4.105741,1.147554,NaN,1.346860,NaN,0.614099,1.297301,NaN,NaN,NaN,1.147545
4,NaN,NaN,NaN,NaN,3.888208,NaN,3.970330,3.979490,NaN,4.010982,NaN,0.920995,1.081111,0.999345,NaN,1.195183,NaN,0.818332,1.236331,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.511905,1.066144,NaN,1.315430,NaN,1.285778,NaN,0.678400,1.023020,0.886803,NaN,4.055996,NaN,NaN,4.156489,4.127622,NaN,NaN,NaN,NaN
96,NaN,1.035022,NaN,1.085834,NaN,0.812558,NaN,1.074543,NaN,0.852806,3.894772,NaN,4.071385,3.935935,NaN,NaN,3.989815,NaN,NaN,4.267142
97,NaN,1.115511,NaN,1.101395,0.878614,NaN,NaN,NaN,1.329319,NaN,4.125190,NaN,4.354638,3.811209,4.144648,NaN,NaN,4.116915,3.887823,NaN
98,NaN,0.850794,NaN,NaN,0.927884,0.669895,NaN,NaN,0.665429,1.387329,NaN,NaN,4.329404,4.111706,3.960197,NaN,NaN,NaN,3.725288,4.122072
99,NaN,NaN,1.413968,0.838720,NaN,NaN,1.094826,0.987888,NaN,1.177387,3.957383,4.136731,NaN,4.026915,NaN,NaN,4.164773,4.104276,NaN,NaN

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/guebin/DL2022/master/_notebooks/2022-09-08-rcmd_anal.csv')

In [9]:
df

     user  item    rating item_name
0       1    15  1.084308       홍차5
1       1     1  4.149209       커피1
2       1    11  1.142659       홍차1
3       1     5  4.033415       커피5
4       1     4  4.078139       커피4
..    ...   ...       ...       ...
995   100    18  4.104276       홍차8
996   100    17  4.164773       홍차7
997   100    14  4.026915       홍차4
998   100     4  0.838720       커피4
999   100     7  1.094826       커피7

[1000 rows x 4 columns]

In [10]:
dls = CollabDataLoaders.from_df(df)

In [14]:
dls.show()

In [44]:
lrnr = collab_learner(dls,y_range=(0,5))

In [59]:
lrnr.fit(30)

In [60]:
lrnr.model

EmbeddingDotBias(
  (u_weight): Embedding(101, 50)
  (i_weight): Embedding(21, 50)
  (u_bias): Embedding(101, 1)
  (i_bias): Embedding(21, 1)
)

In [61]:
X,y = dls.one_batch()

In [62]:
X[0],y[0]

(tensor([38,  6]), tensor([4.0553]))

In [63]:
lrnr.model(X[0:1].to("cuda:0"))

tensor([4.0041], device='cuda:0', grad_fn=<AddBackward0>)

In [64]:
X[0:1]

tensor([[38,  6]])

In [68]:
newX = torch.tensor([[38,13]])

In [69]:
lrnr.model(newX.to("cuda:0"))

tensor([1.0427], device='cuda:0', grad_fn=<AddBackward0>)