In [19]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.3     ✔ dplyr   1.0.7
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [20]:
a=c(1,3,2,3,2)

In [25]:
A=tibble(expand.grid(a,a))

In [26]:
A

   Var1 Var2
1  1    1
2  3    1
3  2    1
4  3    1
5  2    1
6  1    3
7  3    3
8  2    3
9  3    3
10 2    3
11 1    2
12 3    2
13 2    2
14 3    2
15 2    2
16 1    3
17 3    3
18 2    3
19 3    3
20 2    3
21 1    2
22 3    2
23 2    2
24 3    2
25 2    2

In [34]:
A %>% mutate(C=Var1-Var2)  %>% filter(C>0)

  Var1 Var2 C
1 3    1    2
2 2    1    1
3 3    1    2
4 2    1    1
5 3    2    1
6 3    2    1
7 3    2    1
8 3    2    1

In [16]:
as_tibble(expand.grid(a,a))

ERROR: Error in as_tibble(expand.grid(a, a)): could not find function "as_tibble"

In [3]:
A=outer(a,a)

In [12]:
A

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2
[2,] 3    9    6    9    6
[3,] 2    6    4    6    4
[4,] 3    9    6    9    6
[5,] 2    6    4    6    4

In [11]:
sum(!(A[upper.tri(a%o%a, diag=F)] %in% c(1,4,9)))

[1] 8

In [81]:
a%o%a(upper.tri(a%o%a,diag=F)

ERROR: Error in parse(text = x, srcfile = src): <text>:2:0: unexpected end of input
1: a%o%a(upper.tri(a%o%a,diag=F)
   ^

In [79]:
4+3+2+1

[1] 10

In [50]:
a=c(1,5,4,3,2,4,5,2)

In [54]:
sum(a%o%a %in% c(1,4,9,16,25))

[1] 18